In [1]:
import MDAnalysis as mda
from MDAnalysis.coordinates.memory import MemoryReader
import numpy as LyzoData
import numpy as np
import os
def initiate_universe(topology, trajectory):
    universe = mda.Universe(topology, trajectory)
    return universe
if __name__ == '__main__':
    # File Setup
    current_directory = os.getcwd()
    
    topology = os.path.join(current_directory, '/Users/riktapatel/Desktop/Disertation/Data/MD01_1lym_example.gro')
    trajectory = os.path.join(current_directory, '/Users/riktapatel/Desktop/Disertation/Data/MD01_1lym_example.xtc')
     
LyzoData = initiate_universe(topology, trajectory)

#print(LyzoData)
type(LyzoData)
LyzoData.atoms.positions
LyzoData.trajectory
len(LyzoData.atoms)

list(LyzoData.atoms.names)
Calpha = LyzoData.select_atoms("name CA")
# len(u1.atoms)

print(Calpha)

lyzCord = np.random.rand(len(LyzoData.atoms), 3)

print(lyzCord)

<AtomGroup [<Atom 5: CA of type C of resname MET, resid 1 and segid SYSTEM>, <Atom 22: CA of type C of resname ASN, resid 2 and segid SYSTEM>, <Atom 36: CA of type C of resname ILE, resid 3 and segid SYSTEM>, ..., <Atom 2592: CA of type C of resname LYS, resid 162 and segid SYSTEM>, <Atom 2614: CA of type C of resname ASN, resid 163 and segid SYSTEM>, <Atom 2628: CA of type C of resname LEU, resid 164 and segid SYSTEM>]>
[[0.93130974 0.50214847 0.82959612]
 [0.6055559  0.25340172 0.17993287]
 [0.93836322 0.21012591 0.88892366]
 ...
 [0.26734974 0.75623805 0.37094061]
 [0.07755318 0.38956451 0.77017101]
 [0.45231056 0.78416087 0.69212857]]
