In [18]:
%cd /Users/namir_oues/Documents/PhD/Software_Development/MDSubSampler
# import required packages
import joblib
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, cohen_kappa_score, classification_report

/Users/namir_oues/Documents/PhD/Software_Development/MDSubSampler


In [3]:
# load data  
ml_input = np.load("data/50_RMSD_ML_input.npy")
r1 = ml_input.shape
target = np.genfromtxt("data/target50.csv", delimiter=",", skip_header=1)
r2 = target.shape

In [4]:
# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(ml_input, target, test_size=0.3, random_state=42)

In [10]:
# Initialise and train the Logistic Regression model 
model_lr = LogisticRegression()
model_lr.fit(x_train, y_train)
joblib.dump(model_lr, "model_bilrjob")
m_lr = joblib.load("model_bilrjob")

/Users/namir_oues/.pyenv/versions/3.9.1/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
# Perform prediction using the trained model
y_pred = m_lr.predict(x_test)

In [ ]:
# Evaluation performance of the model
print("Accuracy score", accuracy_score(y_test, y_pred))

In [6]:
# Confussion matrix 
cm_bilr = confusion_matrix(y_test, y_pred)
print(confusion_matrix(y_test, y_pred))

[[3472    0 1466]
 [   0 2531   79]
 [1558  389 5505]]


In [8]:
# Classification report
print(classification_report(y_test, y_pred))
report_lr = classification_report(y_test, y_pred, output_dict=True)
df_report_lr = pd.DataFrame(report_lr).transpose()
df_report_lr.to_csv("df_report_bilr.csv")

              precision    recall  f1-score   support

         1.0       0.69      0.70      0.70      4938
         2.0       0.87      0.97      0.92      2610
         3.0       0.78      0.74      0.76      7452

    accuracy                           0.77     15000
   macro avg       0.78      0.80      0.79     15000
weighted avg       0.77      0.77      0.77     15000



In [17]:
# Initialize and train the Random Forest model
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(x_train, y_train)

KeyboardInterrupt: 

In [12]:
# Perform prediciton with the trained model
y_pred = rf_model.predict(x_test)

NameError: name 'rf_model' is not defined

In [13]:
# Evaluation performance of the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy*100:.2f}%")

Accuracy: 76.72%


In [14]:
# Confusion matrix
conf_mat = confusion_matrix(y_test, y_pred)
print(conf_mat)

[[3472    0 1466]
 [   0 2531   79]
 [1558  389 5505]]


In [ ]:
# Calculate Kappa score
# Assuming y_pred are predicted labels and y_test are true labels
kappa_score = cohen_kappa_score(y_test, y_pred)
print(f"Cohen's Kappa Score: {kappa_score}")

In [ ]:
# Initialize and train the SVM classifier
svm_model = SVC(kernel="linear", C=1.0, random_state=42)
svm_model.fit(x_train, y_train)

In [ ]:
# Perform prediction using the trained model
y_pred = svm_model.predict(x_test)

In [ ]:
# Evaluation performance of the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy*100:.2f}%")

In [ ]:
# Confusion matrix
conf_mat = confusion_matrix(y_test, y_pred)
print(conf_mat)

In [ ]:
# Classification report for more detailed metrics 
print(classification_report(y_test, y_pred))